version: "3.7"

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    volumes:
      - ./:/go/src/server
